"""Measured anatomy report: no legacy CDR score/proxy masquerades as atrophy."""

import json
from datetime import datetime, timezone
from uuid import uuid4
from xml.sax.saxutils import escape

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, PageBreak

from backend.app.models import Analysis, Patient, Visit
from backend.app.services.storage import resolve_key
from ml.contracts import ProgressionResult


def build_anatomy_report(patient: Patient, analysis: Analysis, visits: list[Visit]) -> dict:
    result = ProgressionResult.model_validate(analysis.result_json)
    if result.anatomy is None:
        raise ValueError("Missing versioned anatomy result")
    report_id = uuid4().hex
    path = resolve_key(f"reports/{report_id}.pdf")
    path.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    lookup = {v.id: v.label for v in visits}

    def para(value: str, style: str = "BodyText") -> Paragraph:
        return Paragraph(escape(value), styles[style])

    story = [
        para("Alzhio - Longitudinal anatomy research report", "Title"),
        para(patient.code, "Heading2"),
        para("Research Prototype | Not a medical diagnosis"),
        para(f"Method: {result.model_version}; no CDR prediction is generated by this analysis."),
        Spacer(1, 12),
    ]
    for index, item in enumerate(result.anatomy.visits):
        if index:
            story.append(PageBreak())
        story.append(
            para(f"{lookup.get(item.visit_id, 'Visit')} - day {item.days_from_baseline}", "Heading2")
        )
        qc_note = (
            "Automated checks only; unreviewed research measurements."
            if item.qc == "automated_checks_only"
            else "Visual QC status is reported separately from these measurements."
        )
        story.append(para(f"Measured FastSurfer anatomy; QC: {item.qc}. {qc_note}"))
        story.append(
            para(
                f"Hippocampal asymmetry: {item.hippocampal_asymmetry_percent:.2f}% (200*(left-right)/(left+right))."
            )
        )
        rows = [[para("Region"), para("Stats mm3"), para("Mask mm3"), para("Stats/eTIV")]]
        for name, value in item.volumes_mm3.items():
            fraction = item.head_size_ratios.get(name)
            rows.append(
                [
                    para(name.removesuffix("_mm3").replace("_", " ")),
                    para(f"{value:.2f}"),
                    para(f"{item.mask_volumes_mm3[name]:.2f}"),
                    para(f"{fraction:.6f}" if fraction is not None else "unavailable"),
                ]
            )
        table = Table(rows, colWidths=[224, 90, 90, 107], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5f0ef")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.grey),
                ]
            )
        )
        story.append(table)
        story.append(
            para(
                f"Verified source eTIV: {item.etiv_mm3:.2f} mm3 (OASIS cm3 x 1000)."
                if item.etiv_mm3
                else "eTIV normalization unavailable: missing/unverified source units."
            )
        )
        story.append(para(f"Automatic MTA/Koedam: {item.ratings.status}; continuous estimates, no rounding."))
        if item.ratings.status in {"ok", "unreviewed_research"}:
            story.append(
                para(
                    f"MTA left {item.ratings.mta_left:.2f}/4; MTA right {item.ratings.mta_right:.2f}/4; single Koedam PA {item.ratings.posterior_atrophy:.2f}/3. "
                    + (
                        "Unreviewed research estimates; alignment and rating agreement are unverified."
                        if item.ratings.status == "unreviewed_research"
                        else "Rating agreement is unverified."
                    )
                )
            )
        story.extend(para(w) for w in item.ratings.warnings)
        story.append(para(f"Source SHA256: {item.source_sha256}"))
        story.append(para(f"Dictionary: {item.dictionary_version}; FastSurfer {item.fastsurfer_version}."))
        story.append(
            para(
                f"Visual reviewer: {item.reviewer_id or 'not reviewed'}; time: {item.reviewed_at or 'unavailable'}."
            )
        )
        for key in ("nWBV", "MMSE", "CDR"):
            story.append(
                para(
                    f"Source-provided {key}: {item.observed_metadata.get(key) if item.observed_metadata.get(key) is not None else 'missing'}"
                )
            )
    story.append(PageBreak())
    story.append(para("Regional changes", "Heading2"))
    story.append(para(result.anatomy.sign_convention))
    for change in result.anatomy.changes:
        story.append(para(f"Elapsed {change['elapsed_days']} days; QC {change['status']}."))
        rows = [[para("Region"), para("Change mm3"), para("Change %"), para("% / year")]]
        for name, values in change["regions"].items():
            rows.append(
                [
                    para(name.removesuffix("_mm3").replace("_", " ")),
                    para(f"{values['absolute_mm3']:+.2f}"),
                    para(f"{values['percent']:+.2f}"),
                    para(f"{values['annualized_percent']:+.2f}"),
                ]
            )
        if change["regions"]:
            table = Table(rows, colWidths=[241, 90, 90, 90], repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5f0ef")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ]
                )
            )
            story.append(table)
        else:
            story.append(
                para(
                    "Changes are unavailable because paired measurements did not pass the applicable processing checks."
                )
            )
    forecast = result.anatomy.forecast
    story.append(PageBreak())
    story.append(para(f"Predicted anatomy - {forecast.status}", "Heading2"))
    story.append(
        para(
            f"Requested {forecast.interval_days} days after cutoff {forecast.cutoff_visit_id}. Model-generated outputs are not acquired scans."
        )
    )
    if forecast.status == "available":
        story.append(
            para(
                f"Spatial model: {forecast.spatial_model_version}. Release SHA256: {forecast.release_sha256}."
            )
        )
        story.append(
            para(
                f"Checkpoint SHA256: {forecast.model_sha256}. Scalar stats estimates and warped hard-label volumes are different estimators."
            )
        )
        rows = [[para("Region"), para("Predicted mm3"), para("Evaluated interval mm3")]]
        for region, value in forecast.volumes_mm3.items():
            interval = forecast.prediction_intervals.get(region) if forecast.prediction_intervals else None
            rows.append(
                [
                    para(region.removesuffix("_mm3").replace("_", " ")),
                    para(f"{value:.2f}"),
                    para(f"{interval[0]:.2f} - {interval[1]:.2f}" if interval else "unavailable"),
                ]
            )
        table = Table(rows, colWidths=[241, 100, 170], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5f0ef")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(table)
        if forecast.interval_evidence:
            story.append(
                para(
                    f"Interval evidence: {forecast.interval_evidence['method']}; target coverage {forecast.interval_evidence['level']:.0%}; held-out subjects {forecast.interval_evidence['subjects']}. Small-cohort research only."
                )
            )
        else:
            story.append(
                para(
                    "No uncertainty intervals passed physical/held-out coverage gates. None were substituted."
                )
            )
        story.append(para("Future artifact provenance", "Heading2"))
        for artifact in forecast.artifacts:
            story.append(para(f"{artifact.name} ({artifact.kind}); SHA256 {artifact.sha256}"))
    else:
        story.append(para("No future MRI, surface or numeric extrapolation is substituted."))
    story.extend(para(w) for w in [*result.anatomy.forecast.warnings, *result.caveats])

    def footer(canvas, document):
        canvas.setFont("Helvetica", 8)
        canvas.drawString(42, 24, "Research Prototype | Not a medical diagnosis")
        canvas.drawRightString(553, 24, f"Page {document.page}")

    SimpleDocTemplate(str(path), rightMargin=42, leftMargin=42, topMargin=40, bottomMargin=45).build(
        story, onFirstPage=footer, onLaterPages=footer
    )
    metadata = {
        "id": report_id,
        "patientId": patient.id,
        "patientCode": patient.code,
        "ownerId": patient.owner_id,
        "analysisId": analysis.id,
        "outputMode": "anatomy",
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "downloadUrl": f"/api/reports/{report_id}/download",
    }
    resolve_key(f"reports/{report_id}.json").write_text(json.dumps(metadata), encoding="utf-8")
    return {k: v for k, v in metadata.items() if k != "ownerId"}
